### ISSUE TITLE
verify-domains via DNS01 returns with org.shredzone.acme4j.exception.AcmeServerException: No order for ID 1157210309

### ISSUE THREAD

**Issue by olbohlen** [porunov/acme_client#14]
So, I tried to renew my certificates and ran:

```
(1652) toy:/root/acme# java -jar acme_client.jar --command verify-domains -a /etc/pjac/account.key -w /etc/pjac/workdir/ -c /etc/pjac/eenfach.de.csr --challenge-type DNS01
Exception in thread "main" org.shredzone.acme4j.exception.AcmeLazyLoadingException: Order https://acme-v02.api.letsencrypt.org/acme/order/67299589/1157210309
        at org.shredzone.acme4j.AcmeJsonResource.getJSON(AcmeJsonResource.java:68)
        at org.shredzone.acme4j.Order.getAuthorizations(Order.java:107)
        at com.jblur.acme_client.command.certificate.VerifyDomainsCommand.commandExecution(VerifyDomainsCommand.java:51)
        at com.jblur.acme_client.command.ACMECommand.execute(ACMECommand.java:47)
        at com.jblur.acme_client.CommandExecutor.executeACMECommand(CommandExecutor.java:123)
        at com.jblur.acme_client.CommandExecutor.execute(CommandExecutor.java:74)
        at com.jblur.acme_client.Application.main(Application.java:65)
Caused by: org.shredzone.acme4j.exception.AcmeServerException: No order for ID 1157210309
        at org.shredzone.acme4j.connector.DefaultConnection.throwAcmeException(DefaultConnection.java:490)
        at org.shredzone.acme4j.connector.DefaultConnection.performRequest(DefaultConnection.java:417)
        at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:346)
        at org.shredzone.acme4j.connector.DefaultConnection.sendSignedPostAsGetRequest(DefaultConnection.java:147)
        at org.shredzone.acme4j.AcmeJsonResource.update(AcmeJsonResource.java:119)
        at org.shredzone.acme4j.AcmeJsonResource.getJSON(AcmeJsonResource.java:63)
        ... 6 more
(1653) toy:/root/acme# 
```

I verified that my TXT records are updated correctly by queries to googles NS.

My pjac version is 3.0.1 and I run JDK 1.8.0_131:
```
(1656) toy:/root/acme# java -jar acme_client.jar --version
Porunov Java ACME Client (PJAC) v3.0.1
(1657) toy:/root/acme# 
(1657) toy:/root/acme# java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```

**Comment by olbohlen** [comment]
For an unknown reason I had 3 orders in the /etc/pjac/workdir/order_uri_list, I removed the first on that produced the error and then the verify-domains was fine.
