### ISSUE TITLE
Cannot validate challenges - using DNS01

### ISSUE THREAD

**Issue by phelgren** [porunov/acme_client#15]
Not exactly sure what the issue is here.  I went to renew an expired certificate and cannot.  I updated to the latest jar.  I cleared the workdir and digests folder.  Order certificates runs fine.  I copied the values for each challenge to the TXT records ( I use GoDaddy).

I used LetsDebug,net to validate the challenge (at least I think that is what it does).  It says that all is OK.  So, what am I missing?  This has been working fine although it has been a while since I renewed the certificate.  Still looking for a solution.  Ideas?

`2019-12-29 15:45:05 WARN  com.jblur.acme_client.command.certificate.VerifyDomainsCommand:74 - Cannot validate one of challenges for domain: *.ossgarden.org
org.shredzone.acme4j.exception.AcmeException: Challenge invalid: https://acme-v02.api.letsencrypt.org/acme/chall-v3/1999273187/rBdjGA
	at com.jblur.acme_client.manager.ChallengeManager$1.failIfInvalid(ChallengeManager.java:81)
	at com.jblur.acme_client.manager.ValidationService.validate(ValidationService.java:59)
	at com.jblur.acme_client.manager.ValidationService.validate(ValidationService.java:21)
	at com.jblur.acme_client.manager.ChallengeManager.validateChallenge(ChallengeManager.java:57)
	at com.jblur.acme_client.command.certificate.VerifyDomainsCommand.commandExecution(VerifyDomainsCommand.java:72)
	at com.jblur.acme_client.command.ACMECommand.execute(ACMECommand.java:47)
	at com.jblur.acme_client.CommandExecutor.executeACMECommand(CommandExecutor.java:123)
	at com.jblur.acme_client.CommandExecutor.execute(CommandExecutor.java:74)
	at com.jblur.acme_client.Application.main(Application.java:65)
2019-12-29 15:45:10 WARN  com.jblur.acme_client.command.certificate.VerifyDomainsCommand:74 - Cannot validate one of challenges for domain: ossgarden.org
org.shredzone.acme4j.exception.AcmeException: Challenge invalid: https://acme-v02.api.letsencrypt.org/acme/chall-v3/1999273188/4hndhw
	at com.jblur.acme_client.manager.ChallengeManager$1.failIfInvalid(ChallengeManager.java:81)
	at com.jblur.acme_client.manager.ValidationService.validate(ValidationService.java:59)
	at com.jblur.acme_client.manager.ValidationService.validate(ValidationService.java:21)
	at com.jblur.acme_client.manager.ChallengeManager.validateChallenge(ChallengeManager.java:57)
	at com.jblur.acme_client.command.certificate.VerifyDomainsCommand.commandExecution(VerifyDomainsCommand.java:72)
	at com.jblur.acme_client.command.ACMECommand.execute(ACMECommand.java:47)
	at com.jblur.acme_client.CommandExecutor.executeACMECommand(CommandExecutor.java:123)
	at com.jblur.acme_client.CommandExecutor.execute(CommandExecutor.java:74)
	at com.jblur.acme_client.Application.main(Application.java:65)
2019-12-29 15:45:10 ERROR com.jblur.acme_client.command.certificate.VerifyDomainsCommand:100 - Domain *.ossgarden.org is not verified. Please, check warnings.
2019-12-29 15:45:10 ERROR com.jblur.acme_client.command.certificate.VerifyDomainsCommand:100 - Domain ossgarden.org is not verified. Please, check warnings.
`

**Comment by phelgren** [comment]
OK..Self-inflicted.  I have two domain combinations for ossgarden a .org and a .com  I was updating the digest in the .com DNS record so naturally, it didn't match what was generated.

Sorry for the noise.
