### ISSUE TITLE
create the certificate  has a exception: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by johnchen198** [porunov/acme_client#4]
I  create the ssl certificate step by step with the doc.  but some exception has been found.
`2017-05-19 11:05:03 ERROR com.jblur.acme_client.command.registration.RegistrationCommand:29 - Problem with registration/authorization
org.shredzone.acme4j.exception.AcmeNetworkException: Network error
	at org.shredzone.acme4j.connector.DefaultConnection.accept(DefaultConnection.java:201)
	at org.shredzone.acme4j.provider.AbstractAcmeProvider.directory(AbstractAcmeProvider.java:56)
	at org.shredzone.acme4j.Session.readDirectory(Session.java:211)
	at org.shredzone.acme4j.Session.resourceUri(Session.java:186)
	at org.shredzone.acme4j.RegistrationBuilder.create(RegistrationBuilder.java:86)
	at com.jblur.acme_client.manager.RegistrationManager.<init>(RegistrationManager.java:44)
	at com.jblur.acme_client.command.registration.RegistrationCommand.commandExecution(RegistrationCommand.java:27)
	at com.jblur.acme_client.command.ACMECommand.execute(ACMECommand.java:64)
	at com.jblur.acme_client.CommandExecutor.executeACMECommand(CommandExecutor.java:57)
	at com.jblur.acme_client.CommandExecutor.getRegistrationManager(CommandExecutor.java:45)
	at com.jblur.acme_client.CommandExecutor.execute(CommandExecutor.java:94)
	at com.jblur.acme_client.Application.main(Application.java:117)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:911)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:701)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1534)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.shredzone.acme4j.connector.DefaultConnection.accept(DefaultConnection.java:183)
	... 11 common frames omitted
2017-05-19 11:05:03 ERROR com.jblur.acme_client.CommandExecutor:48 - Cannot get account information.
2017-05-19 11:05:04 ERROR com.jblur.acme_client.CommandExecutor:97 - Cannot get registration.`

**Comment by porunov** [comment]
@johnchen198 hello,
Please, provide the command which you used. Seems that the problem is connected with either account key or server access. Are you sure that your CA can be reached from your server?

**Comment by porunov** [comment]
Please, try to update to the newest version of the client.
Reopen this issue if it still exists.
