### ISSUE TITLE
Exception when registering account, but only the first time

### ISSUE THREAD

**Issue by OzoneGrif** [porunov/acme_client#5]
When running:
`java -jar acme_client.jar --log-dir "C:/letsencrypt/" --log-level TRACE --server-url https://acme-staging.api.letsencrypt.org/directory --command add-email --account-key "C:/letsencrypt/gen/account.key" --with-agreement-update --email stuff@domain.com`

The first time, I get this error:

```
2017-07-06 15:26:43 DEBUG org.shredzone.acme4j.connector.DefaultConnection:294 - Location: https://acme-staging.api.letsencrypt.org/acme/reg/2793666
2017-07-06 15:26:43 DEBUG org.shredzone.acme4j.connector.DefaultConnection:325 - Link: terms-of-service -> https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf
2017-07-06 15:26:43 INFO  com.jblur.acme_client.CommandExecutor:62 - Trying to update agreement
2017-07-06 15:26:43 ERROR com.jblur.acme_client.command.registration.UpdateAgreementCommand:42 - Agreement haven't been updated because your provider haven't returned an agreement URL.
java.lang.NullPointerException: null
	at com.jblur.acme_client.command.registration.UpdateAgreementCommand.commandExecution(UpdateAgreementCommand.java:29)
	at com.jblur.acme_client.command.ACMECommand.execute(ACMECommand.java:64)
	at com.jblur.acme_client.CommandExecutor.automaticallyUpdateAgreement(CommandExecutor.java:68)
	at com.jblur.acme_client.CommandExecutor.execute(CommandExecutor.java:106)
	at com.jblur.acme_client.Application.main(Application.java:117)
```

If I run the same command again, it works and I can continue the process.

**Comment by porunov** [comment]
@OzoneGrif 
Please, run `java -jar acme_client.jar --version` and show the output. 
Have you registered the account (C:/letsencrypt/gen/account.key) before run the command `add-email`?

**Comment by OzoneGrif** [comment]
`Porunov Java ACME Client (PJAC) v2.1.1 rev51`

And you're right, I did a command `add-email` without a `register`.
It seemed to work at first because `add-email` actually does register the account.

Thanks for the help.

**Comment by porunov** [comment]
Yes, `add-email` will register the account if it doesn't exists but you should register the account before you use `--with-agreement-update`.

I am closing this issue as it seems to be solved. Feel free to reopen it if needed.

**Comment by OzoneGrif** [comment]
I just finished implementing your client; it works like a charm. 
It's very easy to use and the documentation makes it easy to understand each step.
Kudos.

**Comment by porunov** [comment]
Thank you. Glad to hear it :)
