### ISSUE TITLE
verify-domains fails

### ISSUE THREAD

**Issue by user9209** [porunov/acme_client#6]
java -jar acme_client.jar --version

> Porunov Java ACME Client (PJAC) v2.1.1 rev51

java -version

> java version "1.8.0_144"

java -jar acme_client.jar --log-dir log --command verify-domains -a Account_LetsEncrypt.key -w workdir -d [domain].de -d www.[domain].de -d mail.[domain].de

`Exception in thread "main" org.shredzone.acme4j.exception.AcmeProtocolException:
 Could not load lazily
        at org.shredzone.acme4j.Authorization.load(Authorization.java:214)
        at org.shredzone.acme4j.Authorization.getDomain(Authorization.java:75)
        at com.jblur.acme_client.command.authorization.VerifyDomainsCommand.comm
andExecution(VerifyDomainsCommand.java:37)
        at com.jblur.acme_client.command.ACMECommand.execute(ACMECommand.java:64
)
        at com.jblur.acme_client.CommandExecutor.executeACMECommand(CommandExecu
tor.java:57)
        at com.jblur.acme_client.CommandExecutor.execute(CommandExecutor.java:13
5)
        at com.jblur.acme_client.Application.main(Application.java:117)
Caused by: org.shredzone.acme4j.exception.AcmeServerException: Expired authoriza
tion
        at org.shredzone.acme4j.connector.DefaultConnection.createAcmeException(
DefaultConnection.java:397)
        at org.shredzone.acme4j.connector.DefaultConnection.accept(DefaultConnec
tion.java:199)
        at org.shredzone.acme4j.Authorization.update(Authorization.java:180)
        at org.shredzone.acme4j.Authorization.load(Authorization.java:209)
        ... 6 more
`

Has someone an idea why that fails?

Thanks in Advance

**Comment by porunov** [comment]
Hello @user9209 ,
Sorry for the late response. I was very busy.

The error says that your authorization was expired. I am not sure, but it may be because Lets Encrypt changed its expiration dates for authorizations after you got those authorizations. Nevertheless, I see that it can cause an exception like you posted above. I've fixed this issue in the new version of PJAC (v2.1.2). 

Please download a new version and try to verify your domains again. Make sure you follow this guide:
https://github.com/porunov/acme_client/wiki/Get-a-certificate-for-multiple-domains

Also, do not forget to accept Let's Encrypt agreement after you register a new account.

I would suggest to follow that guide from the beginning because all your authorizations already expired and you have to generate new authorizations.

Please, try to use a new version of PJAC and if it doesn't work then reopen this issue.

Regards,
Oleksandr Porunov
